TASK TURN_AROUND RES (
    PLEASE VAR C = 2 THANKS
    PLEASE VAR B = 0 THANKS
    PLEASE VAR S = -1 THANKS
    FOR C BOUNDARY B STEP S ROTATE LEFT
    RESULT RES
)

TASK IS_WALL_RIGHT RES, ENV(
    SWITCH ENV[6,7,1] TRUE RES = TRUE
    FALSE RES = FALSE
    PLEASE RESULT RES THANKS
)

TASK IS_WALL_LEFT RES, ENV(
    SWITCH ENV[6,5,1] TRUE RES = TRUE
    FALSE RES = FALSE
    PLEASE RESULT RES THANKS
)

TASK IS_WALL_AHEAD RES, ENV(
    SWITCH ENV[5,6,1] TRUE RES = TRUE
    FALSE RES = FALSE
    PLEASE RESULT RES THANKS
)

TASK IS_EXIT_AHEAD RES, ENV(
    SWITCH ENV[5,6,2] TRUE RES = TRUE
    FALSE RES = FALSE
    PLEASE RESULT RES THANKS
)

TASK FINDEXIT (
    VAR C = 1
    PLEASE VAR B = 10000 THANKS
    VAR S = 1
    PLEASE VAR ENV [11,11,2] = FALSE THANKS
    VAR RES = FALSE
    PLEASE VAR CONTINUE = FALSE THANKS

    FOR C BOUNDARY B STEP S (

        PLEASE ENV = GET ENVIRONMENT THANKS
        CONTINUE = FALSE

        PLEASE DO IS_EXIT_AHEAD RES, ENV THANKS
        SWITCH RES TRUE (
            C = B
            PLEASE CONTINUE = TRUE THANKS
        )

        PLEASE DO IS_WALL_RIGHT RES, ENV THANKS
        SWITCH (NOT RES) AND (NOT CONTINUE) TRUE (
            PLEASE ROTATE RIGHT THANKS
            CONTINUE = TRUE
        )

        PLEASE DO IS_WALL_AHEAD RES, ENV THANKS
        SWITCH (NOT RES) AND (NOT CONTINUE) TRUE (
            CONTINUE = TRUE
        )

        DO IS_WALL_LEFT RES, ENV
        SWITCH (NOT RES) AND (NOT CONTINUE) TRUE (
            PLEASE ROTATE LEFT THANKS
            CONTINUE = TRUE
        )

        SWITCH NOT CONTINUE TRUE (
        DO TURN_AROUND RES
        )

        PLEASE MOVE THANKS
    )
    RES = TRUE
)
